spring:
  cloud:
    azure:
      eventhubs:
        connection-string: <AZURE_CONNECTION_STRING>
        processor:
          checkpoint-store:
            container-name: ${AZURE_STORAGE_CONTAINER_NAME}
            account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    stream:
      function:
        definition: supply;consume
      bindings:
        supply-out-0:
          destination: <AZURE_EVENTHUB_NAME>
          group: ${AZURE_EVENTHUB_CONSUMER_GROUP}
        comsume-in-0:
          destination: <AZURE_EVENTHUB_NAME>
      eventhubs:
        bindings:
          supply-out-0:
            producer:
              sync: true
          consume-in-0:
            consumer:
              checkpoint:
                mode: RECORD
