server:
  port: 8081
spring:
  cloud:
    stream:
      function:
        definition: supply
      bindings:
        supply-out-0:
          destination: topic
      dapr:
        binder:
          daprIp: 127.0.0.1
          daprPort: 50001
        bindings:
          supply-out-0:
            producer:
              pubsubName: redis-pubsub
